name: Handle Jira Issue

on:
  workflow_dispatch:
    inputs:
      issue_key:
        description: 'Jira Issue Key'
        required: true

jobs:
  handle-issue:
    runs-on: ubuntu-latest
    environment: automation

    steps:
      - name: Clone private repo manually
        env:
          PAT: ${{ secrets.PAT_READ_PRIVATE_REPO }}
        run: |
          git clone https://$PAT@github.com/suarabhj19/JSM-SNOW-Integration.git sample-app

      - name: Install Java and Groovy
        run: |
          sudo apt-get update -y --fix-missing
          sudo apt-get install -y openjdk-17-jdk groovy

      - name: Create payload.json from Jira inputs
        shell: bash
        run: |
          cat <<EOF > payload.json
          {
            "issue_key": "${{ github.event.inputs.issue_key }}"
          }
          EOF

      - name: Debug payload.json
        run: |
          echo "PWD: $(pwd)"
          ls -l
          cat payload.json

      - name: Run Groovy Script
        run: groovy sample-app/scripts/handle_issue.groovy "$(pwd)/payload.json"
        env:
          JIRA_AUTH: ${{ secrets.JIRA_AUTH }}
          JIRA_URL: ${{ secrets.JIRA_URL }}
          SERVICENOW_INCIDENT_URL: ${{ secrets.SERVICENOW_INCIDENT_URL }}
          SERVICENOW_REQUEST_URL: ${{ secrets.SERVICENOW_REQUEST_URL }}
          SERVICENOW_AUTH: ${{ secrets.SERVICENOW_AUTH }}
