name: Send Email for Jira Issue

on:
  workflow_dispatch:
    inputs:
      issue_data:
        description: 'Issue data as JSON string'
        required: true

jobs:
  notify:
    runs-on: ubuntu-latest
    environment: automation

    steps:
      - name: Clone private repo manually
        env:
          PAT: ${{ secrets.PAT_READ_PRIVATE_REPO }}
        run: |
          git clone https://$PAT@github.com/suarabhj19/JSM-SNOW-Integration.git sample-app

      - name: Set up Java and Groovy
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Groovy
        run: sudo apt-get install -y groovy

      - name: Run Groovy Script
        env:
          ISSUE_DATA: ${{ github.event.inputs.issue_data }}
          JIRA_AUTH: ${{ secrets.JIRA_AUTH }}
          JIRA_URL: ${{ secrets.JIRA_URL }}
          SMTP_EMAIL: ${{ secrets.SMTP_EMAIL }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        run: groovy sample-app/scripts/jira_user_update_notifier.groovy
