name: Send to ServiceNow

on:
  workflow_dispatch:
    inputs:
      issue_data:
        description: 'Issue data as JSON string'
        required: true

jobs:
  sendToSNOW:
    runs-on: ubuntu-latest
    environment: automation

    steps:
      - name: Clone private repo manually
        env:
          PAT: ${{ secrets.PAT_READ_PRIVATE_REPO }}
        run: |
          git clone https://$PAT@github.com/suarabhj19/JSM-SNOW-Integration.git sample-app

      - name: Install Java and Groovy
        run: |
          sudo apt-get update -y --fix-missing
          sudo apt-get install -y openjdk-17-jdk groovy

      - name: Run Groovy script
        env:
          ISSUE_DATA: ${{ inputs.issue_data }}
          JIRA_AUTH: ${{ secrets.JIRA_AUTH }}
          JIRA_URL: ${{ secrets.JIRA_URL }}
          SERVICENOW_INCIDENT_URL: ${{ secrets.SERVICENOW_INCIDENT_URL }}
          SERVICENOW_REQUEST_URL: ${{ secrets.SERVICENOW_REQUEST_URL }}
          SERVICENOW_AUTH: ${{ secrets.SERVICENOW_AUTH }}
          IGNORED_USER_EMAIL: ${{ secrets.IGNORED_USER_EMAIL }}
        run: |
          groovy sample-app/scripts/sendToServiceNow.groovy
