name: Update Jira Priority & Severity

on:
  workflow_dispatch:
    inputs:
      issue_key:
        required: true
        type: string
      urgency:
        required: true
        type: string
      impact:
        required: true
        type: string

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout public repo
        uses: actions/checkout@v3

      - name: Clone private repo manually
        env:
          PAT: ${{ secrets.PAT_READ_PRIVATE_REPO }}
        run: |
          git clone https://$PAT@github.com/suarabhj19/JSM-SNOW-Integration.git

      - name: Install Groovy
        run: |
          sudo apt update
          sudo apt install -y groovy

      - name: Run Groovy script
        env:
          JIRA_AUTH: ${{ secrets.JIRA_AUTH }}
          JIRA_URL: ${{ secrets.JIRA_URL }}
        run: |
          groovy sample-app/scripts/update_priority_severity.groovy \
            "${{ github.event.inputs.issue_key }}" \
            "${{ github.event.inputs.urgency }}" \
            "${{ github.event.inputs.impact }}"
